import { Inter } from "next/font/google";
import "./globals.css";
import "./globalicons.css";
import AuthProvider from "@/contexts/AuthContext";
import DataProvider from "@/contexts/DataContext";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "material-symbols";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
        />
      </Head>
      <body className={inter.className}>
        <AuthProvider>
          <DataProvider>
            <ToastContainer />
            <Header />
            {children}
            <Footer />
          </DataProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
